@url = https://localhost:7177/api

POST  {{url}}/account/register 
Content-Type: application/json

{
    "Name":"Ocph23",
    "Email":"ocph23.test@gmail.com",
    "Password":"Sony@77",
    "Role":"Admin"
}

##########

POST {{url}}/account/login 
Content-Type: application/json

{
    "UserName":"ocph23.test@gmail.com",
    "Password":"Sony@77"
}

#####


#####
